from __future__ import annotations

import unittest

from mcp import Client

from pampapilot.mcp_server import mcp


class MCPServerTests(unittest.IsolatedAsyncioTestCase):
    async def test_server_publishes_only_the_initial_tools(self) -> None:
        async with Client(mcp) as client:
            result = await client.list_tools()

        self.assertEqual(
            {tool.name for tool in result.tools},
            {
                "health_check",
                "get_project_state",
                "discover_project_fx",
                "discover_installed_fx",
                "discover_fx_parameter_domain",
                "preview_saturation_proposal",
                "preview_vocal_rider_proposal",
                "preview_dynamic_resonance_proposal",
                "preview_track_producer_chain",
                "preview_project_track_producer_chain",
                "preview_song_structure",
                "apply_project_song_structure",
                "preview_audio_integrity",
                "preview_project_item_audio_integrity",
                "get_render_settings",
                "get_master_track_state",
                "get_track_state",
                "get_track_items",
                "inspect_track_volume_envelope",
                "apply_vocal_rider_envelope",
                "apply_dynamic_resonance_proposal",
                "apply_project_track_producer_chain",
                "apply_and_compare_project_track_producer_chain",
                "configure_item_fades",
                "create_track",
                "set_track_pan",
                "set_track_volume",
                "set_track_mute",
                "set_track_solo",
                "apply_listening_preparation",
                "apply_track_mix_batch",
                "add_stock_fx",
                "configure_reatune_preset",
                "remove_track_fx",
                "create_effect_bus",
                "configure_ambience_fx",
                "create_bus_send",
                "remove_bus_send",
                "remove_effect_bus",
                "add_master_stock_fx",
                "restore_candidate_render_settings",
                "remove_master_fx",
                "add_instrument",
                "configure_reacomp",
                "configure_waveshaper",
                "configure_dynamic_resonance",
                "configure_reagate",
                "configure_deesser",
                "configure_reaeq_band",
                "import_audio",
                "import_audio_batch",
                "import_midi",
                "import_midi_batch",
                "set_project_tempo",
                "save_project_as",
                "undo_transaction",
                "discover_song_media",
                "analyze_midi",
                "preview_master_delivery_qc",
                "preview_project_master_delivery_qc",
                "render_and_verify_master_candidate",
                "preview_mastering_proposal",
                "apply_mastering_proposal",
                "propose_track_processing",
                "preview_reagate_proposal",
                "apply_reagate_proposal",
                "preview_deesser_proposal",
                "apply_deesser_proposal",
                "preview_ambience_bus_proposal",
                "apply_ambience_bus_proposal",
                "apply_processing_proposal",
                "diagnose_song",
                "preview_song_processing_strategy",
                "preview_production_plan",
                "preview_midi_cleanup",
                "clean_midi_files",
                "preview_song_preparation",
                "prepare_song",
            },
        )
        tools = {tool.name: tool for tool in result.tools}
        self.assertTrue(tools["health_check"].annotations.read_only_hint)
        self.assertTrue(tools["get_project_state"].annotations.read_only_hint)
        self.assertTrue(tools["discover_project_fx"].annotations.read_only_hint)
        self.assertTrue(tools["discover_installed_fx"].annotations.read_only_hint)
        self.assertTrue(tools["discover_fx_parameter_domain"].annotations.read_only_hint)
        self.assertTrue(tools["preview_saturation_proposal"].annotations.read_only_hint)
        self.assertTrue(tools["preview_vocal_rider_proposal"].annotations.read_only_hint)
        self.assertTrue(
            tools["preview_dynamic_resonance_proposal"].annotations.read_only_hint
        )
        self.assertTrue(tools["preview_track_producer_chain"].annotations.read_only_hint)
        self.assertTrue(
            tools["preview_project_track_producer_chain"].annotations.read_only_hint
        )
        self.assertTrue(tools["preview_audio_integrity"].annotations.read_only_hint)
        self.assertTrue(
            tools["preview_project_item_audio_integrity"].annotations.read_only_hint
        )
        self.assertTrue(tools["get_render_settings"].annotations.read_only_hint)
        self.assertTrue(tools["get_master_track_state"].annotations.read_only_hint)
        self.assertFalse(tools["create_track"].annotations.read_only_hint)
        self.assertFalse(tools["create_track"].annotations.destructive_hint)
        self.assertTrue(tools["get_track_items"].annotations.read_only_hint)
        self.assertTrue(tools["inspect_track_volume_envelope"].annotations.read_only_hint)
        self.assertFalse(tools["apply_vocal_rider_envelope"].annotations.read_only_hint)
        self.assertFalse(tools["apply_vocal_rider_envelope"].annotations.destructive_hint)
        self.assertFalse(
            tools["apply_dynamic_resonance_proposal"].annotations.destructive_hint
        )
        self.assertFalse(
            tools["apply_project_track_producer_chain"].annotations.destructive_hint
        )
        self.assertTrue(tools["configure_item_fades"].annotations.idempotent_hint)
        self.assertFalse(tools["configure_item_fades"].annotations.destructive_hint)
        self.assertTrue(tools["set_track_pan"].annotations.idempotent_hint)
        self.assertTrue(tools["set_track_volume"].annotations.idempotent_hint)
        self.assertTrue(tools["set_track_mute"].annotations.idempotent_hint)
        self.assertTrue(tools["set_track_solo"].annotations.idempotent_hint)
        self.assertFalse(tools["apply_listening_preparation"].annotations.read_only_hint)
        self.assertFalse(tools["apply_listening_preparation"].annotations.idempotent_hint)
        self.assertFalse(tools["apply_listening_preparation"].annotations.destructive_hint)
        self.assertTrue(tools["apply_track_mix_batch"].annotations.idempotent_hint)
        self.assertFalse(tools["add_stock_fx"].annotations.idempotent_hint)
        self.assertFalse(tools["add_stock_fx"].annotations.destructive_hint)
        self.assertTrue(tools["configure_reatune_preset"].annotations.idempotent_hint)
        self.assertFalse(tools["configure_reatune_preset"].annotations.destructive_hint)
        self.assertFalse(tools["remove_track_fx"].annotations.destructive_hint)
        self.assertFalse(tools["remove_track_fx"].annotations.idempotent_hint)
        self.assertFalse(tools["create_effect_bus"].annotations.idempotent_hint)
        self.assertTrue(tools["configure_ambience_fx"].annotations.idempotent_hint)
        self.assertTrue(tools["configure_waveshaper"].annotations.idempotent_hint)
        self.assertTrue(
            tools["configure_dynamic_resonance"].annotations.idempotent_hint
        )
        self.assertFalse(tools["create_bus_send"].annotations.idempotent_hint)
        self.assertFalse(tools["remove_bus_send"].annotations.idempotent_hint)
        self.assertFalse(tools["remove_effect_bus"].annotations.idempotent_hint)
        self.assertFalse(tools["add_master_stock_fx"].annotations.destructive_hint)
        self.assertFalse(tools["add_master_stock_fx"].annotations.idempotent_hint)
        self.assertTrue(tools["restore_candidate_render_settings"].annotations.idempotent_hint)
        self.assertFalse(tools["restore_candidate_render_settings"].annotations.destructive_hint)
        self.assertFalse(tools["remove_master_fx"].annotations.idempotent_hint)
        self.assertFalse(tools["remove_master_fx"].annotations.destructive_hint)
        self.assertFalse(tools["add_instrument"].annotations.idempotent_hint)
        self.assertFalse(tools["add_instrument"].annotations.destructive_hint)
        self.assertTrue(tools["configure_reacomp"].annotations.idempotent_hint)
        self.assertFalse(tools["configure_reacomp"].annotations.destructive_hint)
        self.assertTrue(tools["configure_reagate"].annotations.idempotent_hint)
        self.assertFalse(tools["configure_reagate"].annotations.destructive_hint)
        self.assertTrue(tools["configure_deesser"].annotations.idempotent_hint)
        self.assertFalse(tools["configure_deesser"].annotations.destructive_hint)
        self.assertTrue(tools["configure_reaeq_band"].annotations.idempotent_hint)
        self.assertFalse(tools["configure_reaeq_band"].annotations.destructive_hint)
        self.assertFalse(tools["import_audio"].annotations.destructive_hint)
        self.assertFalse(tools["import_audio"].annotations.idempotent_hint)
        self.assertFalse(tools["import_audio_batch"].annotations.idempotent_hint)
        self.assertFalse(tools["import_midi"].annotations.idempotent_hint)
        self.assertFalse(tools["import_midi_batch"].annotations.idempotent_hint)
        self.assertFalse(tools["import_midi"].annotations.destructive_hint)
        self.assertTrue(tools["set_project_tempo"].annotations.idempotent_hint)
        self.assertFalse(tools["save_project_as"].annotations.destructive_hint)
        self.assertTrue(tools["save_project_as"].annotations.idempotent_hint)
        self.assertTrue(tools["undo_transaction"].annotations.destructive_hint)
        self.assertTrue(tools["discover_song_media"].annotations.read_only_hint)
        self.assertTrue(tools["analyze_midi"].annotations.read_only_hint)
        self.assertTrue(tools["preview_master_delivery_qc"].annotations.read_only_hint)
        self.assertTrue(tools["preview_project_master_delivery_qc"].annotations.read_only_hint)
        self.assertFalse(tools["render_and_verify_master_candidate"].annotations.read_only_hint)
        self.assertFalse(tools["render_and_verify_master_candidate"].annotations.destructive_hint)
        self.assertFalse(tools["render_and_verify_master_candidate"].annotations.idempotent_hint)
        self.assertTrue(tools["preview_mastering_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_mastering_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_mastering_proposal"].annotations.destructive_hint)
        self.assertFalse(tools["apply_mastering_proposal"].annotations.idempotent_hint)
        self.assertTrue(tools["propose_track_processing"].annotations.read_only_hint)
        self.assertTrue(tools["preview_reagate_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_reagate_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_reagate_proposal"].annotations.idempotent_hint)
        self.assertFalse(tools["apply_reagate_proposal"].annotations.destructive_hint)
        self.assertTrue(tools["preview_deesser_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_deesser_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_deesser_proposal"].annotations.idempotent_hint)
        self.assertFalse(tools["apply_deesser_proposal"].annotations.destructive_hint)
        self.assertTrue(tools["preview_ambience_bus_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_ambience_bus_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_ambience_bus_proposal"].annotations.idempotent_hint)
        self.assertFalse(tools["apply_ambience_bus_proposal"].annotations.destructive_hint)
        self.assertFalse(tools["apply_processing_proposal"].annotations.read_only_hint)
        self.assertFalse(tools["apply_processing_proposal"].annotations.idempotent_hint)
        self.assertFalse(tools["apply_processing_proposal"].annotations.destructive_hint)
        self.assertTrue(tools["diagnose_song"].annotations.read_only_hint)
        self.assertTrue(tools["preview_song_processing_strategy"].annotations.read_only_hint)
        self.assertTrue(tools["preview_production_plan"].annotations.read_only_hint)
        self.assertTrue(tools["preview_midi_cleanup"].annotations.read_only_hint)
        self.assertFalse(tools["clean_midi_files"].annotations.read_only_hint)
        self.assertFalse(tools["clean_midi_files"].annotations.destructive_hint)
        self.assertTrue(tools["clean_midi_files"].annotations.idempotent_hint)
        self.assertTrue(tools["preview_song_preparation"].annotations.read_only_hint)
        self.assertFalse(tools["prepare_song"].annotations.read_only_hint)
        self.assertFalse(tools["prepare_song"].annotations.destructive_hint)
        self.assertTrue(tools["prepare_song"].annotations.idempotent_hint)


if __name__ == "__main__":
    unittest.main()
